# For most projects, this workflow file will not need changing;
#
name: 'Build and Scan with Wiz CLI'

on:
  push:
    branches: [ "master" ]

    paths-ignore:
      - 'ado.yml'
      - 'buildspec.yml'
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub (uses secrets for security)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 3. Set up Docker Buildx (enables advanced features like caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pythonapp:latest

      # 5. Download and run Wiz CLI to scan the Docker image
      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Wiz CLI Docker Scan
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: |
          ./wizcli scan container-image \
            ${{ secrets.DOCKER_HUB_USERNAME }}/pythonapp:latest \
            --dockerfile ./Dockerfile

      # 6. Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pythonapp:latest

      # 7. Tag Docker image in Wiz
      - name: Wiz CLI Docker Tag
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: |
          ./wizcli docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/pythonapp:latest
